title: Pankaj Dixit
logo: /assets/img/logo.png
description:
  <p align="center">
  <a href="https://github.com/pankd">GitHub</a>
  
  <br>
  I am a software professional with extensive experience in Embedded domain.
  I have worked in Audion FW and Storage domain in the past. At present I am
  working in AI domain.
  <br>
  </p>
theme: jekyll-theme-minimal
